# Site settings
title: Litao Blog
SEOTitle: 涛的博客 | Litao Blog
email: 731334268@qq.com
description: "一些描述"
keyword: "seo 关键词"
url: "https://smalltao.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     smalltao
zhihu_username:     smalltao
github_username:    smalltao
twitter_username:   smalltao
#facebook_username:  smalltao
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# 服务器配置选项
livereload: true      # 您不再需要包含--livereload
reload_port: 5678     # 如果不想使用默认端口

# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: smalltao

# Netease setttings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: smalltao.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "站点地图，<br>不知道填什么，一点不懂审美"
sidebar-avatar: /img/img_long_panda.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true          sidebar-avatar           # 是否启用功能标签
featured-condition-size: 1              # 如果标签的级别超过此条件值，将显示标签



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



## Friends
#friends: [
#    {
#        title: "李涛",
#        href: "https://huangxuan.me/"
#    }
#]
